#!/bin/sh
# waitfor - Wait for a command to exit 0.
# https://github.com/jakeogh/waitfor

min_argcount=2
max_argcount=3
usage="interval command [exit_status]"
test "$#" -ge "${min_argcount}" || { echo "$0 ${usage}" > /dev/stderr && exit 1 ; }
test "$#" -le "${max_argcount}" || { echo "$0 ${usage}" > /dev/stderr && exit 1 ; }

set -o nounset
sleep="${1}"
shift
command="${1}"
shift

if [ $# -eq 1 ];
then
    desired_exit_status="${1}"
    shift
else
    desired_exit_status=0
fi

while `/bin/true`;
do
    ${command}
    if [ $? -eq $desired_exit_status ];
    then
        exit 0
    fi
    sleep "${sleep}" || exit 1
done
